site_name: 幻境技术攻略站
site_url: https://unreal-network.tech

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  icon:
    admonition:
      abstract: material/message-alert
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.select
    - content.code.copy
    - content.code.annotate
  palette: 
    # 自动切换
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 跟随系统

    # 切换至深色模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: 浅色模式
      primary: blue
      accent: pink

    # 切换至浅色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 深色模式
      primary: blue
      accent: pink

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - search
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/44911789

    - icon: fontawesome/brands/github
      link: https://github.com/HoshinoUnreal

    - icon: material/security
      link: https://icp.gov.moe/?keyword=20250071
      name: 萌ICP备20250071号

copyright: Copyright &copy; 2025 星野幻境